### ISSUE TITLE
Categorie UNKNOWN in SORMAS

### ISSUE THREAD

**Issue by MallerBeach** [hzi-braunschweig/SORMAS-Glossary#26]
Dear team,

it is kind of difficult for me where to raise this issue so I post my question here. My issue is related to the German version of SORMAS.

For many binary variables SROMAS offers the posibility to tick "YES", "NO", or "UNKNOWN". A case, for example, may be asked about her pregnancy. Another example is the question whether exposition details are known.

In general, we were wondering with what kind of logic the category "UNKNOWN" was designed for. In my second example, the categories "NO" and "UNKNOWN" may not be perceived as disjunct categories. Something which should typically be avoided in standardised surveys.  

Is "UNKNOWN" meant to document the behavior where a caes/contact refused to answer a question?

Any clarification is appreciated.

**Comment by bernardsilenou** [comment]
@MallerBeach  Raising your request here is fine and your are welcome to raise more that my not be clear to you.

- A binary variable e.g pregnancy has in fact 4 categories, which are: yes, no, unknown and NA/NULL
- Yes (100% sure there is a baby in her womb) and No (100% sure there is no baby in her womb) categories means the data is available. 
- Unknown and NA are all categories of missing data. Here we do not know why the data is missing since there can be infinite reasons for each missing data (called: missing completely at random).
- NA means the person entering the data in SORMAS did not click on the response
- Unknown means the user read the question but can not tell with certainty if it is a yes or a no as response. This can happen if the user is entering the data in SORMAS is doing so using a lab message they got and on the lab message there was record about the pregnancy status and there is no way the user can contact the woman. Another option is if the woman was asked if she is pregnant and she refuse to respond. 
-  On the contrary, it is recommended to have `unknown` as a  response category in a standardized survey. I think we need to get users to understand the meaning  of these terms. If I am a SORMAS user and I so not know if the woman is pregnant, then the right answer is "Unknown" not "NO", because the goal of the question is not directed to my knowledge of the woman's pregnancy. 

I hope this explanation helps

@BasilKaburi  Can you add these definitions to the SORMAS glossary?

**Comment by MallerBeach** [comment]
@bernardsilenou Thanks for clarification.
